# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: afcb8fc1d8aa711769a3ea9381487c975ae93d2c2f4ff6ac5c16f8d16ff5ed7db90301beda5d6fbf6dee760cfe39e2c0282ce9a58f710ac43bfcb4f558586ce2

test:
  secret_key_base: f80d0a225d0cda98ecc8fdd3616eed5d99b598c75a69693b99a8984141ebff9007dfb8007c1ad5272ac333c55de3b8e63053b45bb57c4b6616c640d91a317a00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
